import {
  testDatabaseConnection,
  getLargestPatientId,
  getPatientsOrStatement,
  retreieveAllPatients,
  getPatientById,
  deletePatientById,
  createMedicalStaff,
  getMedicalStaffById,
  listDoctersBySpeciality,
  listAllDocters,
  listAllDoctersWithAllData,
  listAvailableDoctors,
  listAvailableDoctorsBySpeciality,
  createMedicalRecord,
  updateMedicalRecord,
  retrieveAppointmentsForDoctorOnDateRange,
  getDoctorAvailityById,
  retrieveAppointmentSlotsForDoctorOnDateRange,
  updatePatientDetails,
  updateEmergencyContact,
  createAppointmentForPatient,
  getLargestUserId,

} from "./mongoActions";

const mongoActions = {
  testDatabaseConnection,
  getLargestPatientId,
  getPatientsOrStatement,
  retreieveAllPatients,
  getPatientById,
  deletePatientById,
  createMedicalStaff,
  getMedicalStaffById,
  listDoctersBySpeciality,
  listAllDocters,
  listAllDoctersWithAllData,
  listAvailableDoctors,
  listAvailableDoctorsBySpeciality,
  createMedicalRecord,
  updateMedicalRecord,
  retrieveAppointmentsForDoctorOnDateRange,
  getDoctorAvailityById,
  retrieveAppointmentSlotsForDoctorOnDateRange,
  updatePatientDetails,
  updateEmergencyContact,
  createAppointmentForPatient,
  getLargestUserId,
};

export default mongoActions;